TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 0.0

  sim_time: 2.0
  sim_granularity: 0.025
  vx_samples: 20
  vtheta_samples: 40
  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.01
  heading_lookahead: 0.325
