obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.2, -0.2], [-0.2, 0.2], [0.2, 0.2], [0.2, -0.2]]
inflation_radius: 0.55
observation_sources: laser_scan_sensor

laser_scan_sensor: {
  sensor_frame: base_laser,
  data_type: LaserScan,
  topic: scan,
  marking: true,
  clearing: true
}

transform_tolerance: 0.5
map_type: costmap
